version: 0.2

phases:
 install:
  commands:
   - curl -sL https://deb.nodesource.com/setup_14.x | bash -
   - apt-get install -y nodejs
 pre_build:
  commands:
   - npm install
 build:
  commands:
   -npm run build
artifacts:
 files:
  -"**/*"
 discard-paths: no
 base-directory: build

 
    
